version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    only:
      - circle-ci
    executor: win/default # executor type
    steps:
      # Commands are run in a Windows virtual machine environment. Powershell is default shell.
      - checkout
      - run:
          command: |
            cd build\Windows
            .\build-wheel.ps1 `
              -vs_version 9.0 `
              -arch 64 `
              -py_install_dir C:\Python27 `
              -py_installer 2.7.15/python-2.7.15.amd64.msi `
