version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build:
    executor: win/default # executor type

    steps:
      # Commands are run in a Windows virtual machine environment. Powershell is default shell.
      - checkout
      - run:
          command: git config --global url."https://github.com/".insteadOf "git@github.com:"
          shell: powershell.exe
      - run:
          command: $auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          shell: powershell.exe
      - run:
          command: git submodule sync --recursive
          shell: powershell.exe
      - run:
          command: git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force
          shell: powershell.exe

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - windows-build
