name: build-Windows-35

on:
  push:
    branches:
      - windows-build
    paths-ignore:
      - 'examples/**'
      - 'doc/**'
      - README.md

jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        .\build/git-preamble.sh
        cd build\Windows
        .\windows_wheel_maker.ps1
