name: build

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'examples/**'
      - 'doc/**'
      - README.md

jobs:
  all:
    runs-on: ubuntu-18.04
    needs:
      - sdist
      - mac-py27
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: output
        path: dist
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Build full distribution and upload to PyPI.
      run: |
        ls -la dist/
        python -m pip install --upgrade twine==3.1.1
        python -m twine upload -u __token__ -p {{ secrets.testpypi_password }} -r testpypi dist/*
        echo Uploaded to PyPI.

  sdist:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - name: Source distribution
      run: |
        source build/git-preamble.sh
        cd build && ./sdist.sh
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/sdist

  # Mac
  mac-py27:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 2.7
      run: |
        source build/git-preamble.sh
        cd build/OSX && ./build-wheels-27.sh
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output
