name: build-Linux

on:
  push:
    branches-ignore:
      - windows-build
    paths-ignore:
      - 'examples/**'
      - 'doc/**'
      - README.md

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        # use to build sdist
        python-version: "3.5.9"
    - name: Run build
      run: |
        source build/git-preamble.sh
        cd build/Linux && ./build-wheels.sh
