name: build

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'examples/**'
      - 'doc/**'
      - README.md

jobs:
  publish:
    runs-on: macos-10.15
    needs:
      - sdist
      - mac-py27
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: output
        path: build/dist
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # for twine
    - name: Build full distribution and upload to PyPI.
      run: cd build && ./publish.sh ${{ secrets.testpypi_password }} testpypi

  sdist:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.5'
    - name: Source distribution
      run: |
        source build/git-preamble.sh
        cd build && ./sdist.sh
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/sdist

  # Mac
  mac-py27:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 2.7
      run: |
        source build/git-preamble.sh
        cd build/OSX && ./build-wheels-27.sh
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output
