name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        ls -la
        git pull
        cd doc && pwd && ls -la
        cd build/Linux && pwd && ls -la && docker build -t $IMAGE_NAME -f Dockerfile_i686.dockerfile .
